# Generated by Django 4.2.1 on 2023-05-10 15:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Уникальный идентификатор пользователя')),
                ('username', models.CharField(max_length=500, verbose_name='Логин пользователя')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Relations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Уникальный идентификатор связи')),
                ('user', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.RESTRICT, related_name='user', to='user.users', verbose_name='Логин пользователя, установившего связь')),
                ('user_friend', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.RESTRICT, related_name='user_friend', to='user.users', verbose_name='Логин пользователя, с которым связь эта установлена')),
                ('status', models.CharField(max_length=50, verbose_name='Их статус'))
            ],
            options={
                'db_table': 'relations',
            },
        ),
    ]
